- name: this is our first play.
  hosts: webserver1
  tasks:
    - name: "installing"
      apt: name="{{ item }}" state=present
      with_items:
        - vsftpd
        - tree

# above playbook can be modified as 
- name: this is our first play.
  hosts: webserver1
  vars:
    pkg:
      - vsftpd
      - tree
  tasks:
    - name: "installing"
      apt: name="{{ item }}" state=present
      with_items: "{{ pkg }}"
